title: Lucas Tiago
subtitle: Ciência de Dados | Engenharia Elétrica
description: >- # this means to ignore newlines until "baseurl:"
  Página utilizada para compartilhamento de conhecimento relacionados com Ciência de Dados.

url: "" # the base hostname & protocol for your site, e.g. https://example.github.io
baseurl: "" # the subpath of your site, e.g. /blog

urls:
    - text: Home
      url: /
    - text: About
      url: /about
    - text: Blog
      url: /blog
    - text: Gallery
      url: /gallery
#    - text: Shop
#      url : /shop
    - text: Contact
      url : /contact
    - text: Styleguide
      url: /styleguide
    - text: Get Started
      url: /get-started

# Edit Author details (For multi authors check _data/authors.yml)

author_logo: profile.png
author: Lucas Tiago
author_bio: Site para compartilhamento de projetos de ciência de dados.
author_email: "lucastiagooliveira@gmail.com"
author_location: Brasil
#author_website_url: "https://sujaykundu.com"
typewrite-text: Ciência de dados com aplicações práticas.

# Experiences
author_work_experiences:
            - company_name: Associação Paulista para o Desenvolvimento da Medicina
              company_logo: spdm.png
              company_url: https://www.spdm.org.br
              designation: Engenheiro de Manutenção Hospitalar
              description: Responsável por toda estrutura física hospilar.
              visibility: true

# Education
author_education_details:
              - college_logo: ufu.png
                college_name: Universidade Federal de Uberlândia
                college_url: https://ufu.br
                college_degree: Engenharia Elétrica
                description: Graduação
                visibility: true
              - college_logo: ufu.png
                college_name: Universidade Federal de Uberlândia
                college_url: http://www.posgrad.feelt.ufu.br/
                college_degree: Engenharia Elétrica
                description: Mestrado em Qualidade da Energia Elétrica
                visibility: true
              - college_logo: fia.png
                college_name: Fundação Instituto de Administração
                college_url: https://www.fiaonline.com.br/
                college_degree: Pós-graduação em Analytics e Inteligência Artificial
                description: Especialização em ciência de dados.
                visibility: true

# Projects
author_project_details:
              - project_thumbnail: gamershub.png
                project_title: Gamers Hub
                project_description: A Platform built for Gamers and Game Devs
                project_url: https://gamershub.in
                visibility: true
              - project_thumbnail: hack4r.PNG
                project_title: Hack4r
                project_description: A Platform built for Hackers and Penetration Testers
                project_url: https://hack4r.com
                visibility: true

# social links
#twitter_username: johndoe
github_username:  lucastiagooliveira
#facebook_username: johndoe
linkedin_username: lucas-tiago-7a4a1362
#behance_username: johndoe
#instagram_username: johndoe
#medium_username: johndoe
#telegram_username: johndoe
#dribbble_username: johndoe
#flickr_username: johndoe

#for comments ( we got Disqus and Hyvor Commenting, uncomment the one you want to use )

# disqus_shortname: sujay-kundu
hyvor_talk_website_id: 476

# wakatime username (coding activity)
#wakatime_username: lucastiagooliveira

# mailchimp embedded form url (newsletter):
mailchimp_form_url: https://sujaykundu.us10.list-manage.com/subscribe/post?u=50bab1c85eae24ecfb0f68361&amp;id=3a2dd721d0

# formspree (contact form)
formspree_email: lucastiagooliveira@gmail.com

# syntax highlighter
markdown: kramdown
highlighter: rouge
permalink: pretty

# Choose what to show ( can be true or false)
show_author_work_experiences: true
show_author_education_details: true
show_author_project_details: true

# pagination of posts
paginate: 4
per_page: 4
paginate_path: "/blog/page/:num/"

# minify
# compress_html:
#   clippings: all
#   comments: ["<!-- ", " -->"]
#   endings: all
#   ignore:
#     envs: ['development']

# Archives
# jekyll-archives:
#   enabled:
#     - categories
#   layout: archive
#   permalinks:
#     category: '/category/:name/'

collections:
  products:
    output: true
  authors:
    output: true

defaults:
  -
    scope:
      path: "gallery"
    values:
      permalink: /:path/:basename:output_ext
  -
    scope:
      path: ""
      type: authors
    values:
      layout: author
      permalink: /blog/authors/:slug

# Build settings
plugins:
  - jekyll-paginate
  - jekyll-gist
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-menus


# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/

destination: ./build
